#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/optional.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/shared_ptr.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/unique_ptr.h>
#include <nanobind/stl/unordered_set.h>
#include <nanobind/stl/vector.h>
#include <nanobind/trampoline.h>

#include <pacer/datatypes/datatypes.hpp>
#include <pacer/geometry/geometry.hpp>
#include <pacer/gps-source/gps-source.hpp>
#include <pacer/laps/laps.hpp>

namespace nb = nanobind;
using namespace pacer;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_glue_code>  // Autogenerated code

namespace pacer {
// helper type to enable overriding virtual methods in python
class RawGPSSource_trampoline : public RawGPSSource
{
public:
    NB_TRAMPOLINE(RawGPSSource, 8);

    void ReadAccl(std::function<void(IMUSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_accl", // function name (python)
            ReadAccl, // function name (c++)
            param_0 // params
        );
    }
    void ReadGrav(std::function<void(IMUSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_grav", // function name (python)
            ReadGrav, // function name (c++)
            param_0 // params
        );
    }
    void ReadCori(std::function<void(QuatSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_cori", // function name (python)
            ReadCori, // function name (c++)
            param_0 // params
        );
    }
    uint32_t Seek(double target) override
    {
        NB_OVERRIDE_PURE_NAME(
            "seek", // function name (python)
            Seek, // function name (c++)
            target // params
        );
    }
    void Next() override
    {
        NB_OVERRIDE_PURE_NAME(
            "next", // function name (python)
            Next // function name (c++)
        );
    }
    bool IsEnd() override
    {
        NB_OVERRIDE_PURE_NAME(
            "is_end", // function name (python)
            IsEnd // function name (c++)
        );
    }
    std::pair<double, double> CurrentTimeSpan() const override
    {
        NB_OVERRIDE_PURE_NAME(
            "current_time_span", // function name (python)
            CurrentTimeSpan // function name (c++)
        );
    }
    double GetTotalDuration() const override
    {
        NB_OVERRIDE_PURE_NAME(
            "get_total_duration", // function name (python)
            GetTotalDuration // function name (c++)
        );
    }
};
}  // namespace pacer

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

void py_init_module_pacer(nb::module_ &m) {
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_pydef> // Autogenerated code
  ////////////////////    <generated_from:datatypes.hpp>    ////////////////////
  auto pyClassGPSSample =
      nb::class_<pacer::GPSSample>
          (m, "GPSSample", "")
      .def("__init__", [](pacer::GPSSample * self, double lat = double(), double lon = double(), double altitude = double(), double full_speed = double(), double ground_speed = double(), int64_t timestamp_ms = int64_t(), double dop = -1.0, int fix = -1)
      {
          new (self) pacer::GPSSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->lat = lat;
          r_ctor_->lon = lon;
          r_ctor_->altitude = altitude;
          r_ctor_->full_speed = full_speed;
          r_ctor_->ground_speed = ground_speed;
          r_ctor_->timestamp_ms = timestamp_ms;
          r_ctor_->dop = dop;
          r_ctor_->fix = fix;
      },
      nb::arg("lat") = double(), nb::arg("lon") = double(), nb::arg("altitude") = double(), nb::arg("full_speed") = double(), nb::arg("ground_speed") = double(), nb::arg("timestamp_ms") = int64_t(), nb::arg("dop") = -1.0, nb::arg("fix") = -1
      )
      .def_rw("lat", &pacer::GPSSample::lat, "")
      .def_rw("lon", &pacer::GPSSample::lon, "")
      .def_rw("altitude", &pacer::GPSSample::altitude, "")
      .def_rw("full_speed", &pacer::GPSSample::full_speed, "")
      .def_rw("ground_speed", &pacer::GPSSample::ground_speed, "")
      .def_rw("timestamp_ms", &pacer::GPSSample::timestamp_ms, "")
      .def_rw("dop", &pacer::GPSSample::dop, "")
      .def_rw("fix", &pacer::GPSSample::fix, "")
      ;


  auto pyClassPointInTime_GPSSample =
      nb::class_<pacer::PointInTime<GPSSample>>
          (m, "PointInTime_GPSSample", "")
      .def("__init__", [](pacer::PointInTime<GPSSample> * self, pacer::GPSSample point = pacer::GPSSample(), double time = double())
      {
          new (self) pacer::PointInTime<GPSSample>();  // placement new
          auto r_ctor_ = self;
          r_ctor_->point = point;
          r_ctor_->time = time;
      },
      nb::arg("point") = pacer::GPSSample(), nb::arg("time") = double()
      )
      .def_rw("point", &pacer::PointInTime<GPSSample>::point, "")
      .def_rw("time", &pacer::PointInTime<GPSSample>::time, "")
      ;


  auto pyClassVec3f =
      nb::class_<pacer::Vec3f>
          (m, "Vec3f", "")
      .def_rw("x", &pacer::Vec3f::x, "")
      .def_rw("y", &pacer::Vec3f::y, "")
      .def_rw("z", &pacer::Vec3f::z, "")
      .def(nb::init<>())
      .def(nb::init<double, double, double>(),
          nb::arg("x"), nb::arg("y"), nb::arg("z"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Vec3f::operator[]), nb::arg("index"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Vec3f::operator[], nb::const_), nb::arg("index"))
      ;


  auto pyClassIMUSample =
      nb::class_<pacer::IMUSample>
          (m, "IMUSample", " A timestamped 3-axis IMU sample (used for ACCL accelerometer m/s^2 and GRAV gravity\n vector). `time` is on the MEDIA clock (seconds, same basis as the GPS payload spans, so\n it syncs to the video; chapter offsets are applied by the SequentialGPSSource chain just\n like GPS). The three axes are carried in the GoPro stream's native element order\n (ACCL: Z,X,Y in m/s^2; GRAV: a unit gravity-direction vector). The studio layer resolves\n the camera->kart frame transform on top of these raw axes.")
      .def("__init__", [](pacer::IMUSample * self, double x = 0, double y = 0, double z = 0, double time = 0)
      {
          new (self) pacer::IMUSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->x = x;
          r_ctor_->y = y;
          r_ctor_->z = z;
          r_ctor_->time = time;
      },
      nb::arg("x") = 0, nb::arg("y") = 0, nb::arg("z") = 0, nb::arg("time") = 0
      )
      .def_rw("x", &pacer::IMUSample::x, "")
      .def_rw("y", &pacer::IMUSample::y, "")
      .def_rw("z", &pacer::IMUSample::z, "")
      .def_rw("time", &pacer::IMUSample::time, "")
      ;


  auto pyClassQuatSample =
      nb::class_<pacer::QuatSample>
          (m, "QuatSample", " A timestamped orientation quaternion (used for CORI camera-orientation, w,x,y,z).\n `time` is on the MEDIA clock (seconds), same basis as IMUSample / GPS.")
      .def("__init__", [](pacer::QuatSample * self, double w = 1, double x = 0, double y = 0, double z = 0, double time = 0)
      {
          new (self) pacer::QuatSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->w = w;
          r_ctor_->x = x;
          r_ctor_->y = y;
          r_ctor_->z = z;
          r_ctor_->time = time;
      },
      nb::arg("w") = 1, nb::arg("x") = 0, nb::arg("y") = 0, nb::arg("z") = 0, nb::arg("time") = 0
      )
      .def_rw("w", &pacer::QuatSample::w, "")
      .def_rw("x", &pacer::QuatSample::x, "")
      .def_rw("y", &pacer::QuatSample::y, "")
      .def_rw("z", &pacer::QuatSample::z, "")
      .def_rw("time", &pacer::QuatSample::time, "")
      ;
  ////////////////////    </generated_from:datatypes.hpp>    ////////////////////


  ////////////////////    <generated_from:geometry.hpp>    ////////////////////
  auto pyClassPoint =
      nb::class_<pacer::Point>
          (m, "Point", "")
      .def_rw("x", &pacer::Point::x, "")
      .def_rw("y", &pacer::Point::y, "")
      .def(nb::init<>())
      .def(nb::init<double, double>(),
          nb::arg("x"), nb::arg("y"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Point::operator[], nb::const_), nb::arg("index"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Point::operator[]), nb::arg("index"))
      .def("rot",
          &pacer::Point::Rot)
      ;


  m.def("to_point",
      nb::overload_cast<pacer::Point>(pacer::ToPoint), nb::arg("x"));

  m.def("to_point",
      nb::overload_cast<Vec3f>(pacer::ToPoint), nb::arg("v"));

  m.def("to_lon_lat",
      pacer::ToLonLat,
      nb::arg("s"),
      " GPS degrees -> Point{lon, lat}. Named distinctly from ToPoint so a degrees sample can never\n be silently mixed with a local-metres Point behind one overloaded name at a call site.");


  auto pyClassSegment =
      nb::class_<pacer::Segment>
          (m, "Segment", "")
      .def("__init__", [](pacer::Segment * self, pacer::Point first = pacer::Point(), pacer::Point second = pacer::Point())
      {
          new (self) pacer::Segment();  // placement new
          auto r_ctor_ = self;
          r_ctor_->first = first;
          r_ctor_->second = second;
      },
      nb::arg("first") = pacer::Point(), nb::arg("second") = pacer::Point()
      )
      .def_rw("first", &pacer::Segment::first, "")
      .def_rw("second", &pacer::Segment::second, "")
      .def("intersects",
          &pacer::Segment::Intersects,
          nb::arg("fst"), nb::arg("snd"), nb::arg("ratio"),
          " Returns True if segments intersects, if ratio is non-null, it will satisfy:\n   fst * (1 - ratio) + snd  lies  on present segment.")
      .def("__eq__",
          &pacer::Segment::operator==, nb::arg("other"))
      ;


  auto pyClassCoordinateSystem =
      nb::class_<pacer::CoordinateSystem>
          (m, "CoordinateSystem", "")
      .def(nb::init<>())
      .def(nb::init<GPSSample>(),
          nb::arg("origin"))
      .def("local",
          &pacer::CoordinateSystem::Local,
          nb::arg("point"),
          "/ Converts point to local coordinate system.")
      .def("global_",
          &pacer::CoordinateSystem::Global,
          nb::arg("point"),
          "/ Maps local-coordinate point back to gps sample.\n/ N.B. Speed is not preserved.")
      .def("distance",
          &pacer::CoordinateSystem::Distance, nb::arg("from_"), nb::arg("to"))
      ;


  m.def("interpolate",
      nb::overload_cast<pacer::Point, pacer::Point, double>(pacer::Interpolate), nb::arg("from_"), nb::arg("to"), nb::arg("ratio"));

  m.def("interpolate",
      nb::overload_cast<GPSSample, GPSSample, double>(pacer::Interpolate), nb::arg("from_"), nb::arg("to"), nb::arg("ratio"));
  ////////////////////    </generated_from:geometry.hpp>    ////////////////////


  ////////////////////    <generated_from:laps.hpp>    ////////////////////
  auto pyClassLap =
      nb::class_<pacer::Lap>
          (m, "Lap", "")
      .def("__init__", [](pacer::Lap * self, float width = float(), std::vector<PointInTime<GPSSample>> points = std::vector<PointInTime<GPSSample>>(), std::vector<double> cum_distances = std::vector<double>())
      {
          new (self) pacer::Lap();  // placement new
          auto r_ctor_ = self;
          r_ctor_->width = width;
          r_ctor_->points = points;
          r_ctor_->cum_distances = cum_distances;
      },
      nb::arg("width") = float(), nb::arg("points") = std::vector<PointInTime<GPSSample>>(), nb::arg("cum_distances") = std::vector<double>()
      )
      .def_rw("width", &pacer::Lap::width, "")
      .def_rw("points", &pacer::Lap::points, "")
      .def_rw("cum_distances", &pacer::Lap::cum_distances, "")
      .def("fill_distances",
          &pacer::Lap::FillDistances, nb::arg("cs"))
      .def("lap_time",
          &pacer::Lap::LapTime)
      .def("count",
          &pacer::Lap::Count)
      ;


  auto pyClassSectors =
      nb::class_<pacer::Sectors>
          (m, "Sectors", "")
      .def("__init__", [](pacer::Sectors * self, Segment start_line = Segment(), std::vector<Segment> sector_lines = std::vector<Segment>())
      {
          new (self) pacer::Sectors();  // placement new
          auto r_ctor_ = self;
          r_ctor_->start_line = start_line;
          r_ctor_->sector_lines = sector_lines;
      },
      nb::arg("start_line") = Segment(), nb::arg("sector_lines") = std::vector<Segment>()
      )
      .def_rw("start_line", &pacer::Sectors::start_line, "")
      .def_rw("sector_lines", &pacer::Sectors::sector_lines, "")
      ;


  auto pyClassLaps =
      nb::class_<pacer::Laps>
          (m, "Laps", "")
      .def("__init__", [](pacer::Laps * self, pacer::Sectors sectors = pacer::Sectors())
      {
          new (self) pacer::Laps();  // placement new
          auto r_ctor_ = self;
          r_ctor_->sectors = sectors;
      },
      nb::arg("sectors") = pacer::Sectors()
      )
      .def("update",
          &pacer::Laps::Update, "/ Updates all laps given updated start_line and sector_lines")
      .def("pick_random_start",
          &pacer::Laps::PickRandomStart, "/ Picks a starting point for start_line.\n/ Default implementation builds segment perpendicular to median segment.")
      .def("set_coordinate_system",
          &pacer::Laps::SetCoordinateSystem, nb::arg("coordinate_system"))
      .def("min_max",
          &pacer::Laps::MinMax, "/ Gets bounding box for entire thing, might be cached\n/ as depends on points only.")
      .def_rw("sectors", &pacer::Laps::sectors, "")
      .def("laps_count",
          &pacer::Laps::LapsCount)
      .def("lap_entry_speed",
          &pacer::Laps::LapEntrySpeed, nb::arg("lap"))
      .def("lap_time",
          &pacer::Laps::LapTime, nb::arg("lap"))
      .def("sample_count",
          &pacer::Laps::SampleCount, nb::arg("lap"))
      .def("start_timestamp",
          &pacer::Laps::StartTimestamp, nb::arg("lap"))
      .def("get_lap_distance",
          &pacer::Laps::GetLapDistance, nb::arg("index"))
      .def("get_lap",
          &pacer::Laps::GetLap, nb::arg("lap"))
      .def("sector_count",
          &pacer::Laps::SectorCount)
      .def("recorded_sectors",
          &pacer::Laps::RecordedSectors)
      .def("clear_sectors",
          &pacer::Laps::ClearSectors)
      .def("sector_time",
          &pacer::Laps::SectorTime, nb::arg("sector"))
      .def("sector_start_timestamp",
          &pacer::Laps::SectorStartTimestamp, nb::arg("sector"))
      .def("sector_entry_speed",
          &pacer::Laps::SectorEntrySpeed, nb::arg("sector"))
      .def("add_point",
          &pacer::Laps::AddPoint, nb::arg("s"), nb::arg("t"))
      .def("point_count",
          &pacer::Laps::PointCount)
      .def("get_point",
          &pacer::Laps::GetPoint, nb::arg("row"))
      .def("clear_points",
          &pacer::Laps::ClearPoints)
      ;
  ////////////////////    </generated_from:laps.hpp>    ////////////////////


  ////////////////////    <generated_from:gps-source.hpp>    ////////////////////
  auto pyClassRawGPSSource =
      nb::class_<pacer::RawGPSSource, pacer::RawGPSSource_trampoline>
          (m, "RawGPSSource", " Base class for raw GPS source.\n\n Being raw in this context means that it does not provide any meaningful\n timestamps to work with.")
      .def(nb::init<>())
      .def("read_samples",
          &pacer::RawGPSSource::ReadSamples, nb::arg("on_sample"))
      .def("read_accl",
          &pacer::RawGPSSource::ReadAccl, nb::arg("param_0"))
      .def("read_grav",
          &pacer::RawGPSSource::ReadGrav, nb::arg("param_0"))
      .def("read_cori",
          &pacer::RawGPSSource::ReadCori,
          nb::arg("param_0"),
          "CORI: camera-orientation quaternion (w,x,y,z), ~60 Hz, media-clock time.")
      .def("seek",
          &pacer::RawGPSSource::Seek,
          nb::arg("target"),
          "Seeks to data chunk covering target.")
      .def("next",
          &pacer::RawGPSSource::Next, "Proceeds to next piece of data.")
      .def("is_end",
          &pacer::RawGPSSource::IsEnd, "Checks whenever we already reachend end of the stream.")
      .def("current_time_span",
          &pacer::RawGPSSource::CurrentTimeSpan, "Returns current samples' time span.")
      .def("get_total_duration",
          &pacer::RawGPSSource::GetTotalDuration, "Gets total MP4 duration.")
      ;


  auto pyClassGPMFSource =
      nb::class_<pacer::GPMFSource, pacer::RawGPSSource>
          (m, "GPMFSource", " Handler for GPMF track inside MP4 container.\n\n Allows for traversing media file and getting GPS data out of it.\n\n TODO: Provide even more low-level access to underlying samples,\n       might be useful to keep buffer for data in some sort of iterator\n       with option to iterate over GPSSample-s on top of it.")
      .def(nb::init<size_t>(),
          nb::arg("mp4handle"))
      .def(nb::init<const char *>(),
          nb::arg("filename"))
      .def("read_accl",
          &pacer::GPMFSource::ReadAccl, nb::arg("on_sample"))
      .def("read_grav",
          &pacer::GPMFSource::ReadGrav, nb::arg("on_sample"))
      .def("read_cori",
          &pacer::GPMFSource::ReadCori, nb::arg("on_sample"))
      .def("seek",
          &pacer::GPMFSource::Seek,
          nb::arg("target"),
          "Seeks to data chunk covering target.")
      .def("next",
          &pacer::GPMFSource::Next, "Proceeds to next piece of data.")
      .def("is_end",
          &pacer::GPMFSource::IsEnd, "Checks whenever we already reachend end of the stream.")
      .def("current_time_span",
          &pacer::GPMFSource::CurrentTimeSpan, "Returns current samples' time span.")
      .def("get_total_duration",
          &pacer::GPMFSource::GetTotalDuration, "Gets total MP4 duration.")
      ;


  auto pyClassSequentialGPSSource =
      nb::class_<pacer::SequentialGPSSource, pacer::RawGPSSource>
          (m, "SequentialGPSSource", "")
      .def(nb::init<pacer::RawGPSSource *, pacer::RawGPSSource *>(),
          nb::arg("left"), nb::arg("right"))
      .def("get_total_duration",
          &pacer::SequentialGPSSource::GetTotalDuration)
      .def("is_end",
          &pacer::SequentialGPSSource::IsEnd)
      .def("read_accl",
          &pacer::SequentialGPSSource::ReadAccl, nb::arg("on_sample"))
      .def("read_grav",
          &pacer::SequentialGPSSource::ReadGrav, nb::arg("on_sample"))
      .def("read_cori",
          &pacer::SequentialGPSSource::ReadCori, nb::arg("on_sample"))
      .def("seek",
          &pacer::SequentialGPSSource::Seek, nb::arg("target"))
      .def("next",
          &pacer::SequentialGPSSource::Next)
      .def("current_time_span",
          &pacer::SequentialGPSSource::CurrentTimeSpan, "Returns current samples' time span.")
      ;
  ////////////////////    </generated_from:gps-source.hpp>    ////////////////////

  // </litgen_pydef> // Autogenerated code end
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  pyClassGPSSample.def("__repr__", [](const pacer::GPSSample &s) {
    return "GPSSample(lat=" + std::to_string(s.lat) +
           ", lon=" + std::to_string(s.lon) +
           ", altitude=" + std::to_string(s.altitude) +
           ", full_speed=" + std::to_string(s.full_speed) +
           ", ground_speed=" + std::to_string(s.ground_speed) +
           ", dop=" + std::to_string(s.dop) +
           ", fix=" + std::to_string(s.fix) + ")";
  });

  pyClassPoint.def("__repr__", [](const pacer::Point &p) {
    return "Point(x=" + std::to_string(p.x) + ", y=" + std::to_string(p.y) +
           ")";
  });

  pyClassVec3f.def("__repr__", [](const pacer::Vec3f &v) {
    return "Vec3f(x=" + std::to_string(v.x) + ", y=" + std::to_string(v.y) +
           ", z=" + std::to_string(v.z) + ")";
  });

  pyClassSegment.def("__repr__", [](const pacer::Segment &s) {
    return "Segment(first=(" + std::to_string(s.first.x) + ", " +
           std::to_string(s.first.y) + "), second=(" +
           std::to_string(s.second.x) + ", " + std::to_string(s.second.y) +
           "))";
  });
}