#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/optional.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/shared_ptr.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/unique_ptr.h>
#include <nanobind/stl/unordered_set.h>
#include <nanobind/stl/vector.h>
#include <nanobind/trampoline.h>

#include <pacer/datatypes/datatypes.hpp>
#include <pacer/geometry/geometry.hpp>
#include <pacer/gps-source/gps-source.hpp>
#include <pacer/laps/laps.hpp>

namespace nb = nanobind;
using namespace pacer;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_glue_code>  // Autogenerated code

namespace pacer {
// helper type to enable overriding virtual methods in python
class RawGPSSource_trampoline : public RawGPSSource
{
public:
    NB_TRAMPOLINE(RawGPSSource, 9);

    uint32_t ReadSamples(std::function<void(GPSSample, uint32_t, uint32_t)> on_sample) override
    {
        NB_OVERRIDE_NAME(
            "read_samples", // function name (python)
            ReadSamples, // function name (c++)
            on_sample // params
        );
    }
    void ReadAccl(std::function<void(IMUSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_accl", // function name (python)
            ReadAccl, // function name (c++)
            param_0 // params
        );
    }
    void ReadGrav(std::function<void(IMUSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_grav", // function name (python)
            ReadGrav, // function name (c++)
            param_0 // params
        );
    }
    void ReadCori(std::function<void(QuatSample)> param_0) override
    {
        NB_OVERRIDE_NAME(
            "read_cori", // function name (python)
            ReadCori, // function name (c++)
            param_0 // params
        );
    }
    uint32_t Seek(double target) override
    {
        NB_OVERRIDE_PURE_NAME(
            "seek", // function name (python)
            Seek, // function name (c++)
            target // params
        );
    }
    void Next() override
    {
        NB_OVERRIDE_PURE_NAME(
            "next", // function name (python)
            Next // function name (c++)
        );
    }
    bool IsEnd() override
    {
        NB_OVERRIDE_PURE_NAME(
            "is_end", // function name (python)
            IsEnd // function name (c++)
        );
    }
    std::pair<double, double> CurrentTimeSpan() const override
    {
        NB_OVERRIDE_PURE_NAME(
            "current_time_span", // function name (python)
            CurrentTimeSpan // function name (c++)
        );
    }
    double GetTotalDuration() const override
    {
        NB_OVERRIDE_PURE_NAME(
            "get_total_duration", // function name (python)
            GetTotalDuration // function name (c++)
        );
    }
};
}  // namespace pacer

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

void py_init_module_pacer(nb::module_ &m) {
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! <litgen_pydef> // Autogenerated code
  ////////////////////    <generated_from:datatypes.hpp>    ////////////////////
  auto pyClassGPSSample =
      nb::class_<pacer::GPSSample>
          (m, "GPSSample", " A single GPS fix. lat/lon are degrees, altitude is metres, and the two speeds\n are m/s — GPS9 reports both a 2D \"ground\" speed and a 3D \"full\" speed.\n timestamp_ms is the fix time as whole milliseconds on the recording clock.")
      .def("__init__", [](pacer::GPSSample * self, double lat = double(), double lon = double(), double altitude = double(), double full_speed = double(), double ground_speed = double(), int64_t timestamp_ms = int64_t(), double dop = -1.0, int fix = -1)
      {
          new (self) pacer::GPSSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->lat = lat;
          r_ctor_->lon = lon;
          r_ctor_->altitude = altitude;
          r_ctor_->full_speed = full_speed;
          r_ctor_->ground_speed = ground_speed;
          r_ctor_->timestamp_ms = timestamp_ms;
          r_ctor_->dop = dop;
          r_ctor_->fix = fix;
      },
      nb::arg("lat") = double(), nb::arg("lon") = double(), nb::arg("altitude") = double(), nb::arg("full_speed") = double(), nb::arg("ground_speed") = double(), nb::arg("timestamp_ms") = int64_t(), nb::arg("dop") = -1.0, nb::arg("fix") = -1
      )
      .def_rw("lat", &pacer::GPSSample::lat, "")
      .def_rw("lon", &pacer::GPSSample::lon, "")
      .def_rw("altitude", &pacer::GPSSample::altitude, "")
      .def_rw("full_speed", &pacer::GPSSample::full_speed, "")
      .def_rw("ground_speed", &pacer::GPSSample::ground_speed, "")
      .def_rw("timestamp_ms", &pacer::GPSSample::timestamp_ms, "")
      .def_rw("dop", &pacer::GPSSample::dop, "")
      .def_rw("fix", &pacer::GPSSample::fix, "")
      ;


  auto pyClassPointInTime_GPSSample =
      nb::class_<pacer::PointInTime<GPSSample>>
          (m, "PointInTime_GPSSample", " A spatial value tagged with the time it was observed (seconds). `P` is the\n spatial type, so one template covers both the GPS trace (P = GPSSample) and the\n local-metres crossing interpolation (P = Point).")
      .def("__init__", [](pacer::PointInTime<GPSSample> * self, pacer::GPSSample point = pacer::GPSSample(), double time = double())
      {
          new (self) pacer::PointInTime<GPSSample>();  // placement new
          auto r_ctor_ = self;
          r_ctor_->point = point;
          r_ctor_->time = time;
      },
      nb::arg("point") = pacer::GPSSample(), nb::arg("time") = double()
      )
      .def_rw("point", &pacer::PointInTime<GPSSample>::point, "")
      .def_rw("time", &pacer::PointInTime<GPSSample>::time, "")
      ;


  auto pyClassIMUSample =
      nb::class_<pacer::IMUSample>
          (m, "IMUSample", " One 3-axis IMU reading — ACCL (accelerometer, m/s^2) or GRAV (a unit gravity\n direction). `time` is on the MEDIA clock (seconds), the same basis as the GPS\n payload spans, so it lines up with the video; the SequentialGPSSource chain\n applies the per-chapter offset exactly as it does for GPS. Axes are stored in\n the GoPro stream's native order (ACCL: Z,X,Y); the studio layer applies the\n camera->kart frame transform on top.")
      .def("__init__", [](pacer::IMUSample * self, double x = 0, double y = 0, double z = 0, double time = 0)
      {
          new (self) pacer::IMUSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->x = x;
          r_ctor_->y = y;
          r_ctor_->z = z;
          r_ctor_->time = time;
      },
      nb::arg("x") = 0, nb::arg("y") = 0, nb::arg("z") = 0, nb::arg("time") = 0
      )
      .def_rw("x", &pacer::IMUSample::x, "")
      .def_rw("y", &pacer::IMUSample::y, "")
      .def_rw("z", &pacer::IMUSample::z, "")
      .def_rw("time", &pacer::IMUSample::time, "")
      ;


  auto pyClassQuatSample =
      nb::class_<pacer::QuatSample>
          (m, "QuatSample", " One orientation quaternion — CORI (camera orientation), components w,x,y,z.\n `time` is media-clock seconds, matching IMUSample / GPS.")
      .def("__init__", [](pacer::QuatSample * self, double w = 1, double x = 0, double y = 0, double z = 0, double time = 0)
      {
          new (self) pacer::QuatSample();  // placement new
          auto r_ctor_ = self;
          r_ctor_->w = w;
          r_ctor_->x = x;
          r_ctor_->y = y;
          r_ctor_->z = z;
          r_ctor_->time = time;
      },
      nb::arg("w") = 1, nb::arg("x") = 0, nb::arg("y") = 0, nb::arg("z") = 0, nb::arg("time") = 0
      )
      .def_rw("w", &pacer::QuatSample::w, "")
      .def_rw("x", &pacer::QuatSample::x, "")
      .def_rw("y", &pacer::QuatSample::y, "")
      .def_rw("z", &pacer::QuatSample::z, "")
      .def_rw("time", &pacer::QuatSample::time, "")
      ;
  ////////////////////    </generated_from:datatypes.hpp>    ////////////////////


  ////////////////////    <generated_from:geometry.hpp>    ////////////////////
  auto pyClassVec3f =
      nb::class_<pacer::Vec3f>
          (m, "Vec3f", " A 3-component vector in the LOCAL metric frame, used by CoordinateSystem and the\n local<->global conversions. It lives beside Point because it is a geometry\n vector rather than a telemetry sample, and it keeps the full linear + pointwise\n algebra (Global() divides one elementwise by a per-axis radius vector).")
      .def_rw("x", &pacer::Vec3f::x, "")
      .def_rw("y", &pacer::Vec3f::y, "")
      .def_rw("z", &pacer::Vec3f::z, "")
      .def(nb::init<>())
      .def(nb::init<double, double, double>(),
          nb::arg("x"), nb::arg("y"), nb::arg("z"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Vec3f::operator[]), nb::arg("index"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Vec3f::operator[], nb::const_), nb::arg("index"))
      ;


  auto pyClassPoint =
      nb::class_<pacer::Point>
          (m, "Point", "A 2D point / vector (local metres, or lon-lat degrees — the caller decides).")
      .def_rw("x", &pacer::Point::x, "")
      .def_rw("y", &pacer::Point::y, "")
      .def(nb::init<>())
      .def(nb::init<double, double>(),
          nb::arg("x"), nb::arg("y"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Point::operator[], nb::const_), nb::arg("index"))
      .def("__getitem__",
          nb::overload_cast<size_t>(&pacer::Point::operator[]), nb::arg("index"))
      .def("rot",
          &pacer::Point::Rot, " 90-degree left rotation: (x, y) -> (-y, x). Used to build the perpendicular\n for the segment-crossing side test.")
      ;


  m.def("to_lon_lat",
      pacer::ToLonLat,
      nb::arg("s"),
      " GPS degrees -> Point{lon, lat}. Deliberately a different name from ToPoint so a\n degrees sample can never be mixed with a local-metres point behind one\n overload set at a call site.");


  auto pyClassSegment =
      nb::class_<pacer::Segment>
          (m, "Segment", "")
      .def("__init__", [](pacer::Segment * self, pacer::Point first = pacer::Point(), pacer::Point second = pacer::Point())
      {
          new (self) pacer::Segment();  // placement new
          auto r_ctor_ = self;
          r_ctor_->first = first;
          r_ctor_->second = second;
      },
      nb::arg("first") = pacer::Point(), nb::arg("second") = pacer::Point()
      )
      .def_rw("first", &pacer::Segment::first, "")
      .def_rw("second", &pacer::Segment::second, "")
      .def("intersects",
          &pacer::Segment::Intersects,
          nb::arg("fst"), nb::arg("snd"), nb::arg("ratio"),
          " True iff this segment and fst->snd cross PROPERLY. Both straddle tests use\n strict signs, so a touch — an endpoint of either segment lying exactly on the\n other's supporting line — is NOT a crossing (pinned by tests/test_geometry,\n including that a trace vertex sitting exactly on a timing line produces no\n crossing from either adjacent segment). On a True return, if `ratio` is\n non-null it gets the crossing's fraction along fst->snd, so\n fst*(1-ratio) + snd*ratio is the intersection point (Split uses it to\n interpolate the crossing sample/time). `ratio` is untouched on False.")
      .def("__eq__",
          &pacer::Segment::operator==, nb::arg("other"))
      ;


  auto pyClassCoordinateSystem =
      nb::class_<pacer::CoordinateSystem>
          (m, "CoordinateSystem", "")
      .def(nb::init<>())
      .def(nb::init<GPSSample>(),
          nb::arg("origin"))
      .def("local",
          &pacer::CoordinateSystem::Local,
          nb::arg("point"),
          "/ GPS sample -> local-frame point.")
      .def("global_",
          &pacer::CoordinateSystem::Global,
          nb::arg("point"),
          "/ Local-frame point -> GPS sample. N.B. speed is not recovered.")
      .def("distance",
          &pacer::CoordinateSystem::Distance, nb::arg("from_"), nb::arg("to"))
      ;
  ////////////////////    </generated_from:geometry.hpp>    ////////////////////


  ////////////////////    <generated_from:laps.hpp>    ////////////////////
  auto pyClassLap =
      nb::class_<pacer::Lap>
          (m, "Lap", " One materialised lap: the GPS points it covers (interpolated start crossing +\n interior track points + interpolated finish crossing) and the matching\n per-point cumulative odometer.")
      .def("__init__", [](pacer::Lap * self, std::vector<PointInTime<GPSSample>> points = std::vector<PointInTime<GPSSample>>(), std::vector<double> cum_distances = std::vector<double>())
      {
          new (self) pacer::Lap();  // placement new
          auto r_ctor_ = self;
          r_ctor_->points = points;
          r_ctor_->cum_distances = cum_distances;
      },
      nb::arg("points") = std::vector<PointInTime<GPSSample>>(), nb::arg("cum_distances") = std::vector<double>()
      )
      .def_rw("points", &pacer::Lap::points, "")
      .def_rw("cum_distances", &pacer::Lap::cum_distances, "")
      .def("fill_distances",
          &pacer::Lap::FillDistances, nb::arg("cs"))
      .def("lap_time",
          &pacer::Lap::LapTime)
      .def("count",
          &pacer::Lap::Count)
      ;


  auto pyClassSectors =
      nb::class_<pacer::Sectors>
          (m, "Sectors", " The INPUT timing geometry in local metres: the start line plus the intermediate\n sector lines. Confusion trap: the studio does NOT take per-lap sector splits\n from the C++ crossing list these produce — it projects each sector line onto a\n lap's odometer by DISTANCE in Python (studio/session.py, lap_sector_splits),\n because a short line can geometrically miss a crossing on some laps.")
      .def("__init__", [](pacer::Sectors * self, Segment start_line = Segment(), std::vector<Segment> sector_lines = std::vector<Segment>())
      {
          new (self) pacer::Sectors();  // placement new
          auto r_ctor_ = self;
          r_ctor_->start_line = start_line;
          r_ctor_->sector_lines = sector_lines;
      },
      nb::arg("start_line") = Segment(), nb::arg("sector_lines") = std::vector<Segment>()
      )
      .def_rw("start_line", &pacer::Sectors::start_line, "")
      .def_rw("sector_lines", &pacer::Sectors::sector_lines, "")
      ;


  auto pyClassLapArrays =
      nb::class_<pacer::LapArrays>
          (m, "LapArrays", " A lap's per-point data as parallel columns, so the studio layer crosses the\n binding ONCE per lap instead of once per point (it used to call cs.local /\n read full_speed / time / cum_distances in loops over hundreds of points). Every\n column has the same length as the materialised lap (Lap::Count(): start\n crossing + interior points + finish crossing) and they are mutually index-\n aligned:\n   times          media-clock seconds (== Lap::points[i].time)\n   xs, ys         LOCAL metres — CoordinateSystem::Local(point).x|y in the laps'\n                  own coordinate system (the one set via SetCoordinateSystem)\n   full_speed     raw 3D GPS speed m/s (the studio scales to km/h)\n   cum_distances  the lap's gap-aware per-point odometer (== Lap::cum_distances)")
      .def("__init__", [](pacer::LapArrays * self, std::vector<double> times = std::vector<double>(), std::vector<double> xs = std::vector<double>(), std::vector<double> ys = std::vector<double>(), std::vector<double> full_speed = std::vector<double>(), std::vector<double> cum_distances = std::vector<double>())
      {
          new (self) pacer::LapArrays();  // placement new
          auto r_ctor_ = self;
          r_ctor_->times = times;
          r_ctor_->xs = xs;
          r_ctor_->ys = ys;
          r_ctor_->full_speed = full_speed;
          r_ctor_->cum_distances = cum_distances;
      },
      nb::arg("times") = std::vector<double>(), nb::arg("xs") = std::vector<double>(), nb::arg("ys") = std::vector<double>(), nb::arg("full_speed") = std::vector<double>(), nb::arg("cum_distances") = std::vector<double>()
      )
      .def_rw("times", &pacer::LapArrays::times, "")
      .def_rw("xs", &pacer::LapArrays::xs, "")
      .def_rw("ys", &pacer::LapArrays::ys, "")
      .def_rw("full_speed", &pacer::LapArrays::full_speed, "")
      .def_rw("cum_distances", &pacer::LapArrays::cum_distances, "")
      ;


  auto pyClassLaps =
      nb::class_<pacer::Laps>
          (m, "Laps", "")
      .def("__init__", [](pacer::Laps * self, pacer::Sectors sectors = pacer::Sectors())
      {
          new (self) pacer::Laps();  // placement new
          auto r_ctor_ = self;
          r_ctor_->sectors = sectors;
      },
      nb::arg("sectors") = pacer::Sectors()
      )
      .def("update",
          &pacer::Laps::Update, "/ Re-segment the trace against the current start_line / sector_lines.")
      .def("pick_random_start",
          &pacer::Laps::PickRandomStart, "/ A default start line: perpendicular to the local direction near the median\n/ point. Used when no start line has been chosen yet.")
      .def("set_coordinate_system",
          &pacer::Laps::SetCoordinateSystem, nb::arg("coordinate_system"))
      .def("min_max",
          &pacer::Laps::MinMax, "/ Bounding box (min/max lon-lat) over all raw points.")
      .def_rw("sectors", &pacer::Laps::sectors, "")
      .def("laps_count",
          &pacer::Laps::LapsCount)
      .def("lap_entry_speed",
          &pacer::Laps::LapEntrySpeed,
          nb::arg("lap"),
          "/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount().")
      .def("lap_time",
          &pacer::Laps::LapTime,
          nb::arg("lap"),
          "/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount().")
      .def("sample_count",
          &pacer::Laps::SampleCount,
          nb::arg("lap"),
          "/ Out-of-range lap -> 0 (documented empty-return contract, like GetLap).")
      .def("start_timestamp",
          &pacer::Laps::StartTimestamp,
          nb::arg("lap"),
          "/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount().")
      .def("get_lap_distance",
          &pacer::Laps::GetLapDistance,
          nb::arg("index"),
          "/ Throws std::out_of_range (Python: IndexError) if index >= LapsCount().")
      .def("get_lap",
          &pacer::Laps::GetLap, nb::arg("lap"))
      .def("lap_columns",
          &pacer::Laps::LapColumns,
          nb::arg("lap"),
          "/ A lap's per-point columns (see LapArrays) in ONE binding crossing instead of\n/ one per point. Equal (to float round-off) to materialising GetLap(lap) and\n/ reading p.time / cs.Local(p.point).x|y / p.point.full_speed /\n/ cum_distances[i] per point, where cs is the laps' own coordinate system.\n/ Out-of-range lap -> all-empty arrays.")
      .def("sector_count",
          &pacer::Laps::SectorCount)
      .def("recorded_sectors",
          &pacer::Laps::RecordedSectors)
      .def("clear_sectors",
          &pacer::Laps::ClearSectors)
      .def("sector_time",
          &pacer::Laps::SectorTime,
          nb::arg("sector"),
          "/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors().")
      .def("sector_start_timestamp",
          &pacer::Laps::SectorStartTimestamp,
          nb::arg("sector"),
          "/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors().")
      .def("sector_entry_speed",
          &pacer::Laps::SectorEntrySpeed,
          nb::arg("sector"),
          "/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors().")
      .def("add_point",
          &pacer::Laps::AddPoint, nb::arg("s"), nb::arg("t"))
      .def("point_count",
          &pacer::Laps::PointCount)
      .def("get_point",
          &pacer::Laps::GetPoint, nb::arg("row"))
      .def("clear_points",
          &pacer::Laps::ClearPoints)
      .def("track_columns",
          &pacer::Laps::TrackColumns, "/ The WHOLE raw track as parallel columns (see LapArrays) — the LapColumns\n/ idiom over the full trace, so the studio builds its full-trace arrays in ONE\n/ crossing rather than a GetPoint + cs.local per point. times[i] / xs[i] /\n/ ys[i] / full_speed[i] equal GetPoint(i).time, cs.Local(GetPoint(i).point).x|y\n/ and GetPoint(i).point.full_speed for every i in [0, PointCount()), and\n/ cum_distances[i] is the gap-aware odometer from point 0 to point i (the same\n/ cached prefix sum GetLap slices interior distances from). All five columns\n/ have length PointCount(); an empty track yields all-empty arrays.")
      ;
  ////////////////////    </generated_from:laps.hpp>    ////////////////////


  ////////////////////    <generated_from:gps-source.hpp>    ////////////////////
  auto pyClassRawGPSSource =
      nb::class_<pacer::RawGPSSource, pacer::RawGPSSource_trampoline>
          (m, "RawGPSSource", " Abstract source of raw GPS / IMU samples — \"raw\" meaning it hands back fixes\n without imposing a meaningful global timeline of its own.\n\n Return-code convention: the uint32_t-returning methods (ReadSamples, Seek)\n follow the GoPro GPMF parser's codes — 0 (GPMF_OK) is success and any nonzero\n value is some GPMF_ERROR_* diagnostic (GPMFSource::ReadSamples returns\n GPMF_ERROR_MEMORY == 1 when the cursor sits on an empty index). No caller ever\n branches on a particular nonzero code — only zero vs nonzero — so a source\n written outside the parser (a test, a Python subclass) may return 0 for\n success and any nonzero value for \"nothing here\".")
      .def(nb::init<>())
      .def("read_samples",
          &pacer::RawGPSSource::ReadSamples,
          nb::arg("on_sample"),
          " Decode the GPS payload the cursor currently sits on (Seek/Next move it),\n calling on_sample(sample, current_index, total_records) once per fix. Returns\n 0 on success or a nonzero code (e.g. no payload here).\n\n It is a std::function virtual — the same shape as ReadAccl/ReadGrav/ReadCori\n — so a Python subclass can override it through the binding trampoline and\n feed GPS into the engine (for instance as a child of a C++\n SequentialGPSSource). The earlier raw-pointer + function-pointer `Samples`\n virtual could not be trampolined, so Python overrides silently produced\n nothing. The base implementation emits nothing and returns 0; GPMFSource and\n SequentialGPSSource override it.")
      .def("read_accl",
          &pacer::RawGPSSource::ReadAccl, nb::arg("param_0"))
      .def("read_grav",
          &pacer::RawGPSSource::ReadGrav, nb::arg("param_0"))
      .def("read_cori",
          &pacer::RawGPSSource::ReadCori,
          nb::arg("param_0"),
          "CORI is the camera-orientation quaternion (w,x,y,z), ~60 Hz, media-clock time.")
      .def("seek",
          &pacer::RawGPSSource::Seek,
          nb::arg("target"),
          "Move the cursor to the chunk covering `target`.")
      .def("next",
          &pacer::RawGPSSource::Next, "Advance to the next chunk.")
      .def("is_end",
          &pacer::RawGPSSource::IsEnd, "Has the cursor run past the last chunk?")
      .def("current_time_span",
          &pacer::RawGPSSource::CurrentTimeSpan, "Time span of the chunk under the cursor.")
      .def("get_total_duration",
          &pacer::RawGPSSource::GetTotalDuration, "Total media duration.")
      ;


  auto pyClassGPMFSource =
      nb::class_<pacer::GPMFSource, pacer::RawGPSSource>
          (m, "GPMFSource", " A RawGPSSource backed by the GPMF metadata track of an MP4 container: opens the\n file and walks its GPS / IMU / orientation streams.")
      .def(nb::init<const char *>(),
          nb::arg("filename"))
      .def("read_samples",
          &pacer::GPMFSource::ReadSamples,
          nb::arg("on_sample"),
          "See RawGPSSource::ReadSamples for the callback contract.")
      .def("read_accl",
          &pacer::GPMFSource::ReadAccl, nb::arg("on_sample"))
      .def("read_grav",
          &pacer::GPMFSource::ReadGrav, nb::arg("on_sample"))
      .def("read_cori",
          &pacer::GPMFSource::ReadCori, nb::arg("on_sample"))
      .def("seek",
          &pacer::GPMFSource::Seek, nb::arg("target"))
      .def("next",
          &pacer::GPMFSource::Next)
      .def("is_end",
          &pacer::GPMFSource::IsEnd)
      .def("current_time_span",
          &pacer::GPMFSource::CurrentTimeSpan)
      .def("get_total_duration",
          &pacer::GPMFSource::GetTotalDuration)
      ;


  auto pyClassSequentialGPSSource =
      nb::class_<pacer::SequentialGPSSource, pacer::RawGPSSource>
          (m, "SequentialGPSSource", " Concatenates two sources end to end (chapter chaining): the right child's\n timeline is shifted by the left child's duration so the pair reads as one\n continuous recording. `left` may itself be a SequentialGPSSource, so chains of\n any length nest.")
      .def(nb::init<pacer::RawGPSSource *, pacer::RawGPSSource *>(),
          nb::keep_alive<1, 2>(), nb::keep_alive<1, 3>(),
          nb::arg("left"), nb::arg("right"))
      .def("get_total_duration",
          &pacer::SequentialGPSSource::GetTotalDuration)
      .def("is_end",
          &pacer::SequentialGPSSource::IsEnd)
      .def("read_samples",
          &pacer::SequentialGPSSource::ReadSamples, nb::arg("on_sample"))
      .def("read_accl",
          &pacer::SequentialGPSSource::ReadAccl, nb::arg("on_sample"))
      .def("read_grav",
          &pacer::SequentialGPSSource::ReadGrav, nb::arg("on_sample"))
      .def("read_cori",
          &pacer::SequentialGPSSource::ReadCori, nb::arg("on_sample"))
      .def("seek",
          &pacer::SequentialGPSSource::Seek, nb::arg("target"))
      .def("next",
          &pacer::SequentialGPSSource::Next)
      .def("current_time_span",
          &pacer::SequentialGPSSource::CurrentTimeSpan)
      ;
  ////////////////////    </generated_from:gps-source.hpp>    ////////////////////

  // </litgen_pydef> // Autogenerated code end
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END
  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  pyClassGPSSample.def("__repr__", [](const pacer::GPSSample &s) {
    return "GPSSample(lat=" + std::to_string(s.lat) +
           ", lon=" + std::to_string(s.lon) +
           ", altitude=" + std::to_string(s.altitude) +
           ", full_speed=" + std::to_string(s.full_speed) +
           ", ground_speed=" + std::to_string(s.ground_speed) +
           ", dop=" + std::to_string(s.dop) +
           ", fix=" + std::to_string(s.fix) + ")";
  });

  pyClassPoint.def("__repr__", [](const pacer::Point &p) {
    return "Point(x=" + std::to_string(p.x) + ", y=" + std::to_string(p.y) +
           ")";
  });

  pyClassVec3f.def("__repr__", [](const pacer::Vec3f &v) {
    return "Vec3f(x=" + std::to_string(v.x) + ", y=" + std::to_string(v.y) +
           ", z=" + std::to_string(v.z) + ")";
  });

  pyClassSegment.def("__repr__", [](const pacer::Segment &s) {
    return "Segment(first=(" + std::to_string(s.first.x) + ", " +
           std::to_string(s.first.y) + "), second=(" +
           std::to_string(s.second.x) + ", " + std::to_string(s.second.y) +
           "))";
  });
}