from typing import overload, Callable, Tuple, List, Any

# // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# // <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:datatypes.hpp>    ####################

class GPSSample:
    """A single GPS fix. lat/lon are degrees, altitude is metres, and the two speeds
    are m/s — GPS9 reports both a 2D "ground" speed and a 3D "full" speed.
    timestamp_ms is the fix time as whole milliseconds on the recording clock.
    """

    lat: float
    lon: float
    altitude: float
    full_speed: float
    ground_speed: float
    timestamp_ms: int
    # Fix-quality fields, present on GPS9 but not on the legacy GPS5 stream. `dop`
    # is the dilution of precision (strictly positive on a genuine fix) and `fix`
    # the solution type (0 = none, 2 = 2D, 3 = 3D). The negative sentinels stand
    # for "unknown", which downstream reads as "do not quality-filter" — so GPS5
    # data is kept. A negative literal (unlike NaN) also round-trips cleanly into
    # the generated Python stub. The defaults keep pre-existing aggregate
    # initialisers (which omit these two) valid.
    dop: float = -1.0
    fix: int = -1
    def __init__(
        self,
        lat: float = float(),
        lon: float = float(),
        altitude: float = float(),
        full_speed: float = float(),
        ground_speed: float = float(),
        timestamp_ms: int = int(),
        dop: float = -1.0,
        fix: int = -1,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

#  ------------------------------------------------------------------------
#      <template specializations for class PointInTime>
class PointInTime_GPSSample:  # Python specialization for PointInTime<GPSSample>
    """A spatial value tagged with the time it was observed (seconds). `P` is the
    spatial type, so one template covers both the GPS trace (P = GPSSample) and the
    local-metres crossing interpolation (P = Point).
    """

    point: GPSSample
    time: float
    def __init__(self, point: GPSSample = GPSSample(), time: float = float()) -> None:
        """Auto-generated default constructor with named params"""
        pass

#      </template specializations for class PointInTime>
#  ------------------------------------------------------------------------

class IMUSample:
    """One 3-axis IMU reading — ACCL (accelerometer, m/s^2) or GRAV (a unit gravity
    direction). `time` is on the MEDIA clock (seconds), the same basis as the GPS
    payload spans, so it lines up with the video; the SequentialGPSSource chain
    applies the per-chapter offset exactly as it does for GPS. Axes are stored in
    the GoPro stream's native order (ACCL: Z,X,Y); the studio layer applies the
    camera->kart frame transform on top.
    """

    x: float = 0
    y: float = 0
    z: float = 0
    time: float = 0
    def __init__(
        self, x: float = 0, y: float = 0, z: float = 0, time: float = 0
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class QuatSample:
    """One orientation quaternion — CORI (camera orientation), components w,x,y,z.
    `time` is media-clock seconds, matching IMUSample / GPS.
    """

    w: float = 1
    x: float = 0
    y: float = 0
    z: float = 0
    time: float = 0
    def __init__(
        self, w: float = 1, x: float = 0, y: float = 0, z: float = 0, time: float = 0
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

####################    </generated_from:datatypes.hpp>    ####################

####################    <generated_from:geometry.hpp>    ####################

class Vec3f:
    """A 3-component vector in the LOCAL metric frame, used by CoordinateSystem and the
    local<->global conversions. It lives beside Point because it is a geometry
    vector rather than a telemetry sample, and it keeps the full linear + pointwise
    algebra (Global() divides one elementwise by a per-axis radius vector).
    """

    x: float = 0
    y: float = 0
    z: float = 0

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, x: float, y: float, z: float) -> None:
        pass

    def __getitem__(self, index: int) -> float:
        pass

class Point:
    """A 2D point / vector (local metres, or lon-lat degrees — the caller decides)."""

    x: float = 0
    y: float = 0

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, x: float, y: float) -> None:
        pass

    def __getitem__(self, index: int) -> float:
        pass

    def rot(self) -> Point:
        """90-degree left rotation: (x, y) -> (-y, x). Used to build the perpendicular
        for the segment-crossing side test.
        """
        pass

# Local metres -> Point (the Vec3 form keeps x/y and drops z). Both inputs are
# already in the local metric frame, so the result is metres.

def to_lon_lat(s: GPSSample) -> Point:
    """GPS degrees -> Point{lon, lat}. Deliberately a different name from ToPoint so a
    degrees sample can never be mixed with a local-metres point behind one
    overload set at a call site.
    """
    pass

class Segment:
    first: Point
    second: Point

    def intersects(self, fst: Point, snd: Point, ratio: float) -> bool:
        """True iff this segment and fst->snd cross PROPERLY. Both straddle tests use
        strict signs, so a touch — an endpoint of either segment lying exactly on the
        other's supporting line — is NOT a crossing (pinned by tests/test_geometry,
        including that a trace vertex sitting exactly on a timing line produces no
        crossing from either adjacent segment). On a True return, if `ratio` is
        non-null it gets the crossing's fraction along fst->snd, so
        fst*(1-ratio) + snd*ratio is the intersection point (Split uses it to
        interpolate the crossing sample/time). `ratio` is untouched on False.
        """
        pass

    def __eq__(self, other: object) -> bool:
        pass

    def __init__(self, first: Point = Point(), second: Point = Point()) -> None:
        """Auto-generated default constructor with named params"""
        pass

class CoordinateSystem:
    # Maps GPS coordinates to a local metric frame (metres). The forward map is an
    # ECEF-style projection with a height-compensation factor h_c = 1 + alt/R_eq:
    #
    #   x = h_c * R_eq * cos(lat) * cos(lon)
    #   y = h_c * R_eq * cos(lat) * sin(lon)
    #   z = h_c * R_pole * sin(lat)
    #
    # The local basis is the (almost) normalised gradient of that map along
    # lon / lat / altitude, orthogonalised by the radius choice. Good enough for a
    # single track; not a survey-grade datum.

    # The default frame is the IDENTITY basis (dx/dy/dz = the ECEF unit axes, origin
    # at the geocentre), so Local() of a default-constructed system returns the raw
    # ECEF position in metres and Distance() the True 3D chord — rather than the
    # silent zeros an all-zero basis used to yield for code that forgot to install a
    # real CoordinateSystem(origin). Every real pipeline still sets a track-centred
    # origin before any distance is read (verified byte-identical on a real
    # session), so this only changes what FORGOTTEN initialisation produces.
    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, origin: GPSSample) -> None:
        pass

    def local(self, point: GPSSample) -> Vec3f:
        """/ GPS sample -> local-frame point."""
        pass

    def global_(self, point: Vec3f) -> GPSSample:
        """/ Local-frame point -> GPS sample. N.B. speed is not recovered."""
        pass

    def distance(self, from_: GPSSample, to: GPSSample) -> float:
        pass

####################    </generated_from:geometry.hpp>    ####################

####################    <generated_from:laps.hpp>    ####################

class Lap:
    """One materialised lap: the GPS points it covers (interpolated start crossing +
    interior track points + interpolated finish crossing) and the matching
    per-point cumulative odometer.
    """

    points: List[PointInTime[GPSSample]]
    cum_distances: List[float]

    def fill_distances(self, cs: CoordinateSystem) -> None:
        pass

    def lap_time(self) -> float:
        pass

    def count(self) -> int:
        pass

    def __init__(
        self,
        points: List[PointInTime[GPSSample]] = List[PointInTime < GPSSample] > (),
        cum_distances: List[float] = List[float](),
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class Sectors:
    """The INPUT timing geometry in local metres: the start line plus the intermediate
    sector lines. Confusion trap: the studio does NOT take per-lap sector splits
    from the C++ crossing list these produce — it projects each sector line onto a
    lap's odometer by DISTANCE in Python (studio/session.py, lap_sector_splits),
    because a short line can geometrically miss a crossing on some laps.
    """

    start_line: Segment
    sector_lines: List[Segment]
    def __init__(
        self,
        start_line: Segment = Segment(),
        sector_lines: List[Segment] = List[Segment](),
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class LapArrays:
    """A lap's per-point data as parallel columns, so the studio layer crosses the
    binding ONCE per lap instead of once per point (it used to call cs.local /
    read full_speed / time / cum_distances in loops over hundreds of points). Every
    column has the same length as the materialised lap (Lap::Count(): start
    crossing + interior points + finish crossing) and they are mutually index-
    aligned:
      times          media-clock seconds (== Lap::points[i].time)
      xs, ys         LOCAL metres — CoordinateSystem::Local(point).x|y in the laps'
                     own coordinate system (the one set via SetCoordinateSystem)
      full_speed     raw 3D GPS speed m/s (the studio scales to km/h)
      cum_distances  the lap's gap-aware per-point odometer (== Lap::cum_distances)
    """

    times: List[float]
    xs: List[float]
    ys: List[float]
    full_speed: List[float]
    cum_distances: List[float]
    def __init__(
        self,
        times: List[float] = List[float](),
        xs: List[float] = List[float](),
        ys: List[float] = List[float](),
        full_speed: List[float] = List[float](),
        cum_distances: List[float] = List[float](),
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class Laps:
    def update(self) -> None:
        """/ Re-segment the trace against the current start_line / sector_lines."""
        pass

    def pick_random_start(self) -> Segment:
        """/ A default start line: perpendicular to the local direction near the median
        / point. Used when no start line has been chosen yet.
        """
        pass
    # ---------------------------- PRESENTATION -------------------------------//

    def set_coordinate_system(self, coordinate_system: CoordinateSystem) -> None:
        pass

    def min_max(self) -> Tuple[Point, Point]:
        """/ Bounding box (min/max lon-lat) over all raw points."""
        pass
    # -------------------------------- LAPS -----------------------------------//

    sectors: Sectors

    def laps_count(self) -> int:
        pass

    def lap_entry_speed(self, lap: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount()."""
        pass

    def lap_time(self, lap: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount()."""
        pass

    def sample_count(self, lap: int) -> int:
        """/ Out-of-range lap -> 0 (documented empty-return contract, like GetLap)."""
        pass

    def start_timestamp(self, lap: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if lap >= LapsCount()."""
        pass

    def get_lap_distance(self, index: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if index >= LapsCount()."""
        pass

    def get_lap(self, lap: int) -> Lap:
        pass

    def lap_columns(self, lap: int) -> LapArrays:
        """/ A lap's per-point columns (see LapArrays) in ONE binding crossing instead of
        / one per point. Equal (to float round-off) to materialising GetLap(lap) and
        / reading p.time / cs.Local(p.point).x|y / p.point.full_speed /
        / cum_distances[i] per point, where cs is the laps' own coordinate system.
        / Out-of-range lap -> all-empty arrays.
        """
        pass
    # ------------------------------- SECTORS ---------------------------------//

    def sector_count(self) -> int:
        pass

    def recorded_sectors(self) -> int:
        pass

    def clear_sectors(self) -> None:
        pass

    def sector_time(self, sector: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors()."""
        pass

    def sector_start_timestamp(self, sector: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors()."""
        pass

    def sector_entry_speed(self, sector: int) -> float:
        """/ Throws std::out_of_range (Python: IndexError) if sector >= RecordedSectors()."""
        pass
    # ------------------------------ RAW POINTS -------------------------------//

    def add_point(self, s: GPSSample, t: float) -> None:
        pass

    def point_count(self) -> int:
        pass
    # / Throws std::out_of_range (Python: IndexError) if row >= PointCount().
    def get_point(self, row: int) -> PointInTime_GPSSample:
        pass

    def clear_points(self) -> None:
        pass

    def track_columns(self) -> LapArrays:
        """/ The WHOLE raw track as parallel columns (see LapArrays) — the LapColumns
        / idiom over the full trace, so the studio builds its full-trace arrays in ONE
        / crossing rather than a GetPoint + cs.local per point. times[i] / xs[i] /
        / ys[i] / full_speed[i] equal GetPoint(i).time, cs.Local(GetPoint(i).point).x|y
        / and GetPoint(i).point.full_speed for every i in [0, PointCount()), and
        / cum_distances[i] is the gap-aware odometer from point 0 to point i (the same
        / cached prefix sum GetLap slices interior distances from). All five columns
        / have length PointCount(); an empty track yields all-empty arrays.
        """
        pass

    def __init__(self, sectors: Sectors = Sectors()) -> None:
        """Auto-generated default constructor with named params"""
        pass

####################    </generated_from:laps.hpp>    ####################

####################    <generated_from:gps-source.hpp>    ####################

class RawGPSSource:
    """Abstract source of raw GPS / IMU samples — "raw" meaning it hands back fixes
    without imposing a meaningful global timeline of its own.

    Return-code convention: the uint32_t-returning methods (ReadSamples, Seek)
    follow the GoPro GPMF parser's codes — 0 (GPMF_OK) is success and any nonzero
    value is some GPMF_ERROR_* diagnostic (GPMFSource::ReadSamples returns
    GPMF_ERROR_MEMORY == 1 when the cursor sits on an empty index). No caller ever
    branches on a particular nonzero code — only zero vs nonzero — so a source
    written outside the parser (a test, a Python subclass) may return 0 for
    success and any nonzero value for "nothing here".
    """

    def __init__(self) -> None:
        pass

    def read_samples(  # overridable
        self, on_sample: Callable[[GPSSample, int, int], None]
    ) -> int:
        """Decode the GPS payload the cursor currently sits on (Seek/Next move it),
        calling on_sample(sample, current_index, total_records) once per fix. Returns
        0 on success or a nonzero code (e.g. no payload here).

        It is a std::function virtual — the same shape as ReadAccl/ReadGrav/ReadCori
        — so a Python subclass can override it through the binding trampoline and
        feed GPS into the engine (for instance as a child of a C++
        SequentialGPSSource). The earlier raw-pointer + function-pointer `Samples`
        virtual could not be trampolined, so Python overrides silently produced
        nothing. The base implementation emits nothing and returns 0; GPMFSource and
        SequentialGPSSource override it.
        """
        pass
    # Read the timestamped IMU streams (accelerometer / gravity) across the WHOLE
    # source. Each sample's `time` is on the MEDIA clock (seconds), spread across
    # the payload span so it lines up with the GPS spans and the video; a
    # multi-chapter source shifts later chapters by the cumulative duration (see
    # SequentialGPSSource) onto one continuous global clock. The base is a no-op;
    # GPMFSource / SequentialGPSSource override.
    #
    # ACCL is a 3-axis accelerometer in m/s^2 (native order Z,X,Y); GRAV is a unit
    # gravity vector (native order, permuted vs ACCL — the studio layer resolves
    # that).
    def read_accl(self, param_0: Callable[[IMUSample], None]) -> None:  # overridable
        pass

    def read_grav(self, param_0: Callable[[IMUSample], None]) -> None:  # overridable
        pass

    def read_cori(self, param_0: Callable[[QuatSample], None]) -> None:  # overridable
        """CORI is the camera-orientation quaternion (w,x,y,z), ~60 Hz, media-clock time."""
        pass

    def seek(self, target: float) -> int:  # overridable (pure virtual)
        """Move the cursor to the chunk covering `target`."""
        pass

    def next(self) -> None:  # overridable (pure virtual)
        """Advance to the next chunk."""
        pass

    def is_end(self) -> bool:  # overridable (pure virtual)
        """Has the cursor run past the last chunk?"""
        pass

    def current_time_span(self) -> Tuple[float, float]:  # overridable (pure virtual)
        """Time span of the chunk under the cursor."""
        pass

    def get_total_duration(self) -> float:  # overridable (pure virtual)
        """Total media duration."""
        pass

class GPMFSource(RawGPSSource):
    """A RawGPSSource backed by the GPMF metadata track of an MP4 container: opens the
    file and walks its GPS / IMU / orientation streams.
    """

    # C++ ONLY: take ownership of an already-opened gpmf-parser MP4 handle. Kept out
    # of the Python bindings (see generate-bindings.py) because a stray integer
    # from Python would be reinterpreted as an mp4-object pointer and crash.
    def __init__(self, filename: str) -> None:
        pass

    def read_samples(self, on_sample: Callable[[GPSSample, int, int], None]) -> int:
        """See RawGPSSource::ReadSamples for the callback contract."""
        pass

    def read_accl(self, on_sample: Callable[[IMUSample], None]) -> None:
        pass

    def read_grav(self, on_sample: Callable[[IMUSample], None]) -> None:
        pass

    def read_cori(self, on_sample: Callable[[QuatSample], None]) -> None:
        pass

    def seek(self, target: float) -> int:
        pass

    def next(self) -> None:
        pass

    def is_end(self) -> bool:
        pass

    def current_time_span(self) -> Tuple[float, float]:
        pass

    def get_total_duration(self) -> float:
        pass

class SequentialGPSSource(RawGPSSource):
    """Concatenates two sources end to end (chapter chaining): the right child's
    timeline is shifted by the left child's duration so the pair reads as one
    continuous recording. `left` may itself be a SequentialGPSSource, so chains of
    any length nest.
    """

    def __init__(self, left: RawGPSSource, right: RawGPSSource) -> None:
        pass

    def get_total_duration(self) -> float:
        pass

    def is_end(self) -> bool:
        pass

    def read_samples(self, on_sample: Callable[[GPSSample, int, int], None]) -> int:
        pass

    def read_accl(self, on_sample: Callable[[IMUSample], None]) -> None:
        pass

    def read_grav(self, on_sample: Callable[[IMUSample], None]) -> None:
        pass

    def read_cori(self, on_sample: Callable[[QuatSample], None]) -> None:
        pass

    def seek(self, target: float) -> int:
        pass

    def next(self) -> None:
        pass

    def current_time_span(self) -> Tuple[float, float]:
        pass

####################    </generated_from:gps-source.hpp>    ####################

# // </litgen_stub> // Autogenerated code end
# // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
